export const ActionType = {
  SET_LOADING_STATUS: "SET_LOADING_STATUS",
  ADD_CITY: "ADD_CITY",
  ADD_CITY_ERROR: "ADD_CITY_ERROR",
  DELETE_CITY: "DELETE_CITY",
  UPDATE_CITIES_WEATHER: "UPDATE_CITIES_WEATHER",
  REFRESH_CITY_WEATHER: "REFRESH_CITY_WEATHER",
  GET_HOURLY_CITY_TEMPERATURE: "GET_HOURLY_CITY_TEMPERATURE",
  ADD_CURRENT_CITY: "ADD_CURRENT_CITY",
};
